# Generated by Django 2.2.5 on 2022-02-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20220202_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='beths',
            new_name='baths',
        ),
    ]
