# Generated by Django 2.2.5 on 2022-02-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20220204_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='baths',
            new_name='bathrooms',
        ),
    ]
